site_name: DART - Diagnostic Analysis and Reporting Tool 

extra:
    feature:
        tabs: false
pages:
- Home: index.md
- 'Guides':
  - 'Overview': guide-overview.md
  - 'Query': guide-queries.md
  - 'Report': guide-report.md
  - 'Admin': guide-admin.md
- About: about.md
